# Generated by Django 4.1 on 2022-08-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('zipcode', models.TextField(max_length=10)),
            ],
        ),
    ]
