# Generated by Django 4.0.3 on 2022-10-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='blog_name',
        ),
    ]
