# Generated by Django 4.0.3 on 2022-10-28 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_alter_author_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='mod_date',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='number_of_comments',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='number_of_pingbacks',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='rating',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tagline',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_app.themeblog'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='body_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='headline',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='themeblog',
            name='theme',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
