# Generated by Django 4.0.3 on 2022-10-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0004_remove_entry_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tagline',
            new_name='body_text',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='body_text',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='headline',
        ),
        migrations.AddField(
            model_name='blog',
            name='headline',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ThemeBlog',
        ),
    ]
