# Generated by Django 4.0.3 on 2022-11-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0010_entry_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mod_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
